# Numpy Project - Part 1: The Sudoku Board

This is the first part of our Numpy project. This project is about playing Sudoku with Numpy. Sounds like fun, right? 😃

This first part will focus on array creation and the structure of the game: the board.

In [1]:
import numpy as np

We'll use the following board as an example:

<img src="https://user-images.githubusercontent.com/872296/68136001-49d21400-ff03-11e9-8750-acb846e23046.png" width="600px">

We'll create boards from strings, as follows:

In [2]:
puzzle_str = """
020080050
400006800
600453970
000002090
004000600
010300000
057134009
009600005
030020080
"""

This is already solved, there's nothing to do here, but if you have a second, please try reading and understanding what this line does:

In [3]:
[list(line.strip()) for line in puzzle_str.split('\n') if line.strip()]

[['0', '2', '0', '0', '8', '0', '0', '5', '0'],
 ['4', '0', '0', '0', '0', '6', '8', '0', '0'],
 ['6', '0', '0', '4', '5', '3', '9', '7', '0'],
 ['0', '0', '0', '0', '0', '2', '0', '9', '0'],
 ['0', '0', '4', '0', '0', '0', '6', '0', '0'],
 ['0', '1', '0', '3', '0', '0', '0', '0', '0'],
 ['0', '5', '7', '1', '3', '4', '0', '0', '9'],
 ['0', '0', '9', '6', '0', '0', '0', '0', '5'],
 ['0', '3', '0', '0', '2', '0', '0', '8', '0']]

As any meaningful code we create and find useful, we'll try refactoring it into its own reusable function:

In [6]:
def string_puzzle_to_arr(puzzle):
    return np.array([list(line.strip()) for line in puzzle.split('\n') if line.strip()], dtype=int)

In [7]:
puzzle = string_puzzle_to_arr(puzzle_str)
puzzle

array([[0, 2, 0, 0, 8, 0, 0, 5, 0],
       [4, 0, 0, 0, 0, 6, 8, 0, 0],
       [6, 0, 0, 4, 5, 3, 9, 7, 0],
       [0, 0, 0, 0, 0, 2, 0, 9, 0],
       [0, 0, 4, 0, 0, 0, 6, 0, 0],
       [0, 1, 0, 3, 0, 0, 0, 0, 0],
       [0, 5, 7, 1, 3, 4, 0, 0, 9],
       [0, 0, 9, 6, 0, 0, 0, 0, 5],
       [0, 3, 0, 0, 2, 0, 0, 8, 0]])

👆 you can use this `puzzle` variable to practice before moving to the actual assignment:
* get rows
* get columns
* get _blocks_ (3x3 squares)


<img width="452" src="https://user-images.githubusercontent.com/872296/68136806-a3870e00-ff04-11e9-87d4-489485501fa3.png">

#### Getting a row

Rows and columns are 0-indexed, as other Python collections. That means that the _third_ row (or column) is actually index `2`. Practice here how to get the row with index `2`, you should get: 

In [10]:
third_row = puzzle[2]

expected:

In [11]:
assert np.array_equal(third_row, np.array([6, 0, 0, 4, 5, 3, 9, 7, 0]))

#### Getting a column

Columns are also 0-indexed. Practice here how to get the _5th_ column, which is index `4`, you should get:

In [14]:
fifth_col = puzzle[:, 4]

In [15]:
assert np.array_equal(fifth_col, np.array([8, 0, 5, 0, 0, 0, 3, 0, 2]))

#### Getting a column

Blocks are 3x3 squares with 9 numbers, which by sudoku rules, can't contain repeated numbers, refresher image again:

<img width="452" src="https://user-images.githubusercontent.com/872296/68136806-a3870e00-ff04-11e9-87d4-489485501fa3.png">

We'll be referencing blocks by 2 indices, the first one vertically (top-bottom), the second one horizontally (left-right).

The special characteristic of a block, is that it'll be a matrix, not a vector (2 dimensional, 3x3 matrix).

For example, block `(2, 2)` is:

In [16]:
np.array([
    [0, 0, 9],
    [0, 0, 5],
    [0, 8, 0]
])

array([[0, 0, 9],
       [0, 0, 5],
       [0, 8, 0]])

And block `(0, 1)` is:

In [17]:
np.array([
    [0, 8, 0],
    [0, 0, 6],
    [4, 5, 3]
])

array([[0, 8, 0],
       [0, 0, 6],
       [4, 5, 3]])

Time to practice, your task is to extract the block `(1, 2)`:

In [18]:
block_1_2 = puzzle[3:6, 6:]

In [19]:
expected_block = np.array([
    [0, 9, 0],
    [6, 0, 0],
    [0, 0, 0]
])

In [20]:
assert np.array_equal(block_1_2, expected_block)

### Iterating the board

We'll implement now 3 methods that will be useful later:

* `iter_rows()`
* `iter_columns()`
* `iter_blocks()`

These methods are extremely simple, they'll just return a list of all the rows/columns/blocks to be used later. For example, I'll start providing the code to iterate all the rows in the board:

In [22]:
for row in puzzle:
    print(f"Row: {row}")

Row: [0 2 0 0 8 0 0 5 0]
Row: [4 0 0 0 0 6 8 0 0]
Row: [6 0 0 4 5 3 9 7 0]
Row: [0 0 0 0 0 2 0 9 0]
Row: [0 0 4 0 0 0 6 0 0]
Row: [0 1 0 3 0 0 0 0 0]
Row: [0 5 7 1 3 4 0 0 9]
Row: [0 0 9 6 0 0 0 0 5]
Row: [0 3 0 0 2 0 0 8 0]


Now it's your turn:

##### a) Iterate over the columns:

In [23]:
# Your Solution
for col in puzzle.T:
    print(f'Col: {col}')

Col: [0 4 6 0 0 0 0 0 0]
Col: [2 0 0 0 0 1 5 0 3]
Col: [0 0 0 0 4 0 7 9 0]
Col: [0 0 4 0 0 3 1 6 0]
Col: [8 0 5 0 0 0 3 0 2]
Col: [0 6 3 2 0 0 4 0 0]
Col: [0 8 9 0 6 0 0 0 0]
Col: [5 0 7 9 0 0 0 0 8]
Col: [0 0 0 0 0 0 9 5 0]


##### b) Iterate over the blocks:

In [25]:
# Your Solution
for row in range(0, 9, 3):
    for col in range(0, 9, 3):
        print(f'{puzzle[row: row + 3, col : col +3]}')

[[0 2 0]
 [4 0 0]
 [6 0 0]]
[[0 8 0]
 [0 0 6]
 [4 5 3]]
[[0 5 0]
 [8 0 0]
 [9 7 0]]
[[0 0 0]
 [0 0 4]
 [0 1 0]]
[[0 0 2]
 [0 0 0]
 [3 0 0]]
[[0 9 0]
 [6 0 0]
 [0 0 0]]
[[0 5 7]
 [0 0 9]
 [0 3 0]]
[[1 3 4]
 [6 0 0]
 [0 2 0]]
[[0 0 9]
 [0 0 5]
 [0 8 0]]


## Time to test your code

It's finally time to test your code. We'll use an OOP approach for our board. Here you'll find the `Board` class with empty methods. We'll provide some tests in the notebook, but your job will be to move your `Board` class to the file `sudoku.py` once it's ready. Let's get started:

In [65]:
# Fill the methods here

class Board:
    def __init__(self, puzzle):
        if isinstance(puzzle, str):
            self.puzzle = self.string_puzzle_to_arr(puzzle)
        elif isinstance(puzzle, np.ndarray):
            self.puzzle = puzzle
        else:
            raise ValueError("Invalid input type. Must be either a string or a numpy array.")
        
        # Add arr attribute for backward compatibility with the tests
        self.arr = self.puzzle

    def string_puzzle_to_arr(self, puzzle_str):
        return np.array([[int(char) for char in line.strip()] for line in puzzle_str.split('\n') if line.strip()], dtype=int)

    def get_row(self, row_index):
        return self.puzzle[row_index]

    def get_column(self, col_index):
        return self.puzzle[:, col_index]

    def get_block(self, pos_1, pos_2):
        return self.puzzle[pos_1 * 3: (pos_1 * 3) + 3, pos_2 * 3: (pos_2 * 3) + 3]
   
    def iter_rows(self):
        return [self.get_row(i) for i in range(self.puzzle.shape[0])]

    def iter_columns(self):
        return [self.get_column(i) for i in range(self.puzzle.shape[1])]

    def iter_blocks(self):
        return [self.get_block(i // 3, i % 3) for i in range(9)]

##### 1) Test: creating boards

There are two ways of creating `Board`s: 1) from strings 2) from other Numpy arrays. Let's test that they both work:

In [68]:
puzzle_str = """
020080050
400006800
600453970
000002090
004000600
010300000
057134009
009600005
030020080
"""

In [69]:
board = Board(puzzle_str)

In [70]:
expected = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]
])

In [71]:
assert np.array_equal(board.arr, expected)

In [72]:
board = Board(np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]
]))

In [73]:
assert np.array_equal(board.arr, expected)

##### 2) Test: get rows

In [74]:
board = Board(puzzle_str)

In [75]:
assert np.array_equal(board.get_row(2), np.array([6, 0, 0, 4, 5, 3, 9, 7, 0]))

##### 3) Test: get columns

In [76]:
assert np.array_equal(board.get_column(4), np.array([8, 0, 5, 0, 0, 0, 3, 0, 2]))

##### 4) Test: get blocks

In [77]:
assert np.array_equal(board.get_block(1, 2), np.array([
    [0, 9, 0],
    [6, 0, 0],
    [0, 0, 0]   
]))

In [78]:
assert np.array_equal(board.get_block(2, 2), np.array([
    [0, 0, 9],
    [0, 0, 5],
    [0, 8, 0]
]))

##### 5) Test: iter_rows()

In [79]:
# Collect all rows from iter_rows() into a numpy array
rows_from_board = np.array(list(board.iter_rows()))

# Now compare it to the expected array
expected = np.array([
    [0, 2, 0, 0, 8, 0, 0, 5, 0],
    [4, 0, 0, 0, 0, 6, 8, 0, 0],
    [6, 0, 0, 4, 5, 3, 9, 7, 0],
    [0, 0, 0, 0, 0, 2, 0, 9, 0],
    [0, 0, 4, 0, 0, 0, 6, 0, 0],
    [0, 1, 0, 3, 0, 0, 0, 0, 0],
    [0, 5, 7, 1, 3, 4, 0, 0, 9],
    [0, 0, 9, 6, 0, 0, 0, 0, 5],
    [0, 3, 0, 0, 2, 0, 0, 8, 0]
])

# Perform the assertion
assert np.array_equal(rows_from_board, expected)


##### 6) Test: iter_columns()

In [80]:
# Collect all columns from iter_columns() into a numpy array
columns_from_board = np.array(list(board.iter_columns()))

# Define the expected columns
expected_columns = np.array([
    [0, 4, 6, 0, 0, 0, 0, 0, 0],
    [2, 0, 0, 0, 0, 1, 5, 0, 3],
    [0, 0, 0, 0, 4, 0, 7, 9, 0],
    [0, 0, 4, 0, 0, 3, 1, 6, 0],
    [8, 0, 5, 0, 0, 0, 3, 0, 2],
    [0, 6, 3, 2, 0, 0, 4, 0, 0],
    [0, 8, 9, 0, 6, 0, 0, 0, 0],
    [5, 0, 7, 9, 0, 0, 0, 0, 8],
    [0, 0, 0, 0, 0, 0, 9, 5, 0]
])

# Perform the assertion
assert np.array_equal(columns_from_board, expected_columns)


## Ready to move on?

Now copy your `Board` class into the file `sudoku.py`, we'll be using it in our next steps. Once you're ready, you can try running the tests using:


In [66]:
!py.test test_part_1.py

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python311\Scripts\py.test.exe\__main__.py", line 4, in <module>
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python311\Lib\site-packages\pytest.py", line 9, in <module>
    from _pytest.config import (
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\config.py", line 16, in <module>
    import _pytest.assertion
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\assertion\__init__.py", line 8, in <module>
    from _pytest.assertion import util
  File "C:\Users\gaming\AppData\Local\Programs\Python\Python311\Lib\site-packages\_pytest\assertion\util.py", line 8, in <module>
    from collections import Sequence
ImportError: cannot import name 'Sequence' from 'collections' (C:\Users\gaming\AppData\Local\Programs\P

Now head to Part 2! `2. Sudoku Validity.ipynb`.